version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"    
    expose:
      - '3306'
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - divviup-client-network
  redis:
    image: 'bitnami/redis:latest'
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    expose:
      - '6379'
    ports:
      - 6379:6379
    volumes: 
      - redis-data:/data

  # collector:
  #   image: us-west2-docker.pkg.dev/divviup-artifacts-public/janus/janus_interop_collector:0.7.0-prerelease-2
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   environment:
  #     RUST_BACKTRACE: 1 

networks:
  divviup-client-network:

volumes:
  db-data:
  redis-data: