version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"    
    expose:
      - '3306'
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - divviup-client-network

networks:
  divviup-client-network:

volumes:
  db-data: